name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Generate coverage report
      env:
        DATABASE_CLUSTER_ID: $${{secrets.DATABASE_CLUSTER_ID}}
        DATABASE_USERNAME: $${secrets.DATABASE_USERNAME}}
        DATBASE_PASSWORD: $${{secrets.DATBASE_PASSWORD}}
        DATABASE_HOST: $${{secrets.DATABASE_HOST}}
        DISCORD_TOKEN: $${{secrets.DISCORD_TOKEN}}
      run: |
        INTEGRATION_TEST=true go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage report
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
        
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.1.0

